FROM spark_docker_v2

# Build the package
RUN python setup.py sdist bdist_wheel

# Add the distribution
COPY src src

RUN python -m build src

# Install the package
RUN pip install dist/*.whl

# Add necessary data
ADD tests tests

# Run unit tests
RUN python -m unittest discover tests