FROM spark_docker_base

# Build the package
#RUN python setup.py sdist bdist_wheel

# Add the distribution
COPY src src

# Add the config files
ADD pyproject.toml pyproject.toml

RUN python -m build

# Install the package
RUN pip install dist/*.whl

# Add necessary data
ADD tests tests

# Run unit tests
RUN python -m unittest discover tests