FROM spark_docker_v1

# Add neccessary data
ADD superannotate_databricks_connector superannotate_databricks_connector
ADD setup.py setup.py
ADD tests tests

# Build the package
RUN python setup.py sdist bdist_wheel

# Add the distribution
ADD dist dist

# Install the package
RUN pip install dist/*.whl

# Run unit tests
RUN python -m unittest discover tests